#pragma once
void NhapMang(int*& a, int& n);
void NhapMangSoThuc(float*& b, int& n);
void Xuatmang(int* p, int n);
float Bai122(float* arr,int n);
void Bai124(int* p, int n);
bool Bai125(int* p);
float Bai221(int* a, int n);
void Bai127(int* &a, int n);
void SwapNumber(int& m, int& n);
void Bai266(int*& a, int &n, int m, int k);
void Bai271(int*& a, int& n, int k);
void CapPhat(int** p, int n);
void NhapMaTranCap2(int**& a, int& m, int* &b);
void XuatMaTranCap2(int** a, int m, int *b);
void HuyMaTranCap2(int** a, int m);
float Bai317(int** a, int m, int* b);
bool KiemtraSoNguyenTo(int a);
void XoaDong(int** &a, int &m , int* &b,int k );
void ThemDong(int**& a, int*& b, int& m, int k);
void NhapMangmotchieu(int*& a, int &n);
bool TimMax(int x, int y);
bool TimMin(int x, int y);
int Timgiatri(int* a, int n, bool (*dieukien)(int x, int y));
float TimViTriLonNhat(int* a, int n, bool (*dieukien)(int n));
bool SoAm(int n);
bool SoNguyenTo(int n);
int Timlengchar(char* a);
void CopyChar(char*& destination, char* src);

